name: easystate
description: EasyState is the simplest and the easiest state management for Flutter.
version: 1.0.2
homepage: https://github.com/thruthesky/easystate

environment:
  sdk: ">=3.2.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
