name: easystate
description: EasyState is the simplest and the easiest state management for Flutter.
version: 1.0.1
homepage: https://github.com/thruthesky/easystate

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
