name: easystate
description: 가장 쉬운 상태 관리 패키지
version: 0.0.5
homepage: https://github.com/thruthesky/easystate

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: